/* tslint:disable */
// @ts-nocheck

const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

const environment = argv.environment;
const isProduction = environment === 'prod';

require('dotenv').config({path: `./${isProduction ? '.env' : '.env.development'}`});

const envDirectory = './src/environments';
const prodEnv = 'environment.prod.ts';
const devEnv = 'environment.ts';

function writeFileUsingFs(targetPath, environmentFileContent){
  writeFile(targetPath, environmentFileContent,
    function(err){
      if(err){
        console.log(err);
      }
      if(environmentFileContent !== ''){
        console.log(`Wrote variables to ${targetPath}`);
      }
    }
  );
}

//create environment directory if it does not exist

if(!existsSync(envDirectory)){
  mkdirSync(envDirectory);
}

//create environment files f they don't exist
writeFileUsingFs(`${envDirectory}/${prodEnv}`,'');
writeFileUsingFs(`${envDirectory}/${devEnv}`,'');

//Dynamically compiling environment files

const targetPath = isProduction ? `${envDirectory}/${prodEnv}` : `${envDirectory}/${devEnv}`;

const environmentFileContent = `
  //File autogenerated by running src/assets/scripts/setEnv.ts

  export const environment = {
    firebaseConfig: {
      projectId: '${process.env.projectId}',
      appId: '${process.env.appId}',
      storageBucket: '${process.env.storageBucket}',
      apiKey: '${process.env.apiKey}',
      authDomain: '${process.env.authDomain}',
      messagingSenderId: '${process.env.messagingSenderId}',
      measurementId: '${process.env.measurementId}',
    },
    production: ${isProduction}
  };
`;

//appending data into the target file
writeFileUsingFs(targetPath, environmentFileContent);

/* tslint:enable */
